### PR TITLE
feat: adds tsup

### PR DESCRIPTION
**Pull request by moltar**
Adds `tsup` construct.

Later will refactor it to also add it to the project construct with some sane defaults.

### CODE REVIEW

**Review by Pagebakers — APPROVED** [review]
Good enough for now, but next iteration I'd like to see tsup.config.ts instead of adding config to package.json

**Comment by Pagebakers** [comment]
Tried it again, but getting this error now, when running build.

```ts
➤ YN0000: Done in 0s 724ms
➤ YN0000: [@stackgen/core]: Process started
➤ YN0000: [@stackgen/core]: Error: Cannot find module 'node:path'
➤ YN0000: [@stackgen/core]: Require stack:
➤ YN0000: [@stackgen/core]: - /Users/eelco/Development/appulse/stackgen/node_modules/rollup/dist/shared/rollup.js
➤ YN0000: [@stackgen/core]: - /Users/eelco/Development/appulse/stackgen/node_modules/rollup/dist/rollup.js
➤ YN0000: [@stackgen/core]: - /Users/eelco/Development/appulse/stackgen/node_modules/tsup/dist/index.js
➤ YN0000: [@stackgen/core]: - /Users/eelco/Development/appulse/stackgen/node_modules/tsup/dist/chunk-PDM6VDW3.js
➤ YN0000: [@stackgen/core]: - /Users/eelco/Development/appulse/stackgen/node_modules/tsup/dist/cli-default.js
➤ YN0000: [@stackgen/core]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
➤ YN0000: [@stackgen/core]:     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
➤ YN0000: [@stackgen/core]:     at Module.require (internal/modules/cjs/loader.js:957:19)
➤ YN0000: [@stackgen/core]:     at require (internal/modules/cjs/helpers.js:88:18)
➤ YN0000: [@stackgen/core]:     at Object.<anonymous> (/Users/eelco/Development/appulse/stackgen/node_modules/rollup/dist/shared/rollup.js:12:19)
➤ YN0000: [@stackgen/core]:     at Module._compile (internal/modules/cjs/loader.js:1068:30)
➤ YN0000: [@stackgen/core]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
➤ YN0000: [@stackgen/core]:     at Module.load (internal/modules/cjs/loader.js:933:32)
➤ YN0000: [@stackgen/core]:     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
➤ YN0000: [@stackgen/core]:     at Module.require (internal/modules/cjs/loader.js:957:19)
➤ YN0000: [@stackgen/core]: Process exited (exit code 1), completed in 0s 543ms
```

**Comment by moltar** [comment]
What are the steps to get this error?

**Comment by moltar** [comment]
Fat finger.

**Comment by moltar** [comment]
> Error: Cannot find module 'node:path'

I think it might be that your Node version is < 16?

Can you run and paste output here:

```sh
npx -q envinfo@latest --system --binaries --markdown
```

**Comment by moltar** [comment]
> Good enough for now, but next iteration I'd like to see tsup.config.ts instead of adding config to package.json

Agreed. I also prefer to use file-based configs, rather than stuff everything into `package.json`.

I didn't find if `tsup` had a mergeConfig option though, and otherwise it'll be not possible to overwrite generated config for the end-user.

With the `package.json` I figured the users would be able to just create `tsup.config.ts` and it will take presedence over `package.json` (it is last in the list of places tsup checks for configs)

**Comment by moltar** [comment]
Maybe we can do:

```
tsup.stackgen.config.ts
```

Which exports partial config, and then in:

```
tsup.config.ts
```

We can just spread it:

```TypeScript
import { partialStackgenConfig } "./tsup.stackgen.config"
tsupConfig({
  ...partialStackgenConfig,
  // ... user config
})
```

**Comment by moltar** [comment]
Added `tsx` back via --loader flag. I think we need it, regardless, because during the synth, we are doing a require on the `.stackgenrc.ts` file which is TypeScript and Node alone cannot parse it.

**Comment by Pagebakers** [comment]
The error was because I was working on my old Mac, which was still on node 14. Fixed.

>> With the package.json I figured the users would be able to just create tsup.config.ts and it will take presedence over package.json (it is last in the list of places tsup checks for configs)

This sounds good actually, if it works.

**Pull request merged**
